config/routes.rb
Rails.application.routes.draw do
  resources :search_suggestions
  resources :ratings
  resources :coauthors
  resources :reviews
  root :to => redirect('/books')
  devise_for :users , :controllers => { registrations: 'registrations' }
  resources :books 

  resources :categories
  resources :ratings, only: :update
  get 'books/:id/review', to: 'reviews#review'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/coauthor.rb
class Coauthor < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/coauthors_controller.rb
class CoauthorsController < ApplicationController
  before_action :set_coauthor, only: [:show, :edit, :update, :destroy]

  # GET /coauthors
  # GET /coauthors.json
  def index
    @coauthors = Coauthor.all
  end

  # GET /coauthors/1
  # GET /coauthors/1.json
  def show
  end

  # GET /coauthors/new
  def new
    @coauthor = Coauthor.new
  end

  # GET /coauthors/1/edit
  def edit
  end

  # POST /coauthors
  # POST /coauthors.json
  def create
    @coauthor = Coauthor.new(coauthor_params)

    respond_to do |format|
      if @coauthor.save
        format.html { redirect_to @coauthor, notice: 'Coauthor was successfully created.' }
        format.json { render :show, status: :created, location: @coauthor }
      else
        format.html { render :new }
        format.json { render json: @coauthor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coauthors/1
  # PATCH/PUT /coauthors/1.json
  def update
    respond_to do |format|
      if @coauthor.update(coauthor_params)
        format.html { redirect_to @coauthor, notice: 'Coauthor was successfully updated.' }
        format.json { render :show, status: :ok, location: @coauthor }
      else
        format.html { render :edit }
        format.json { render json: @coauthor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coauthors/1
  # DELETE /coauthors/1.json
  def destroy
    @coauthor.destroy
    respond_to do |format|
      format.html { redirect_to coauthors_url, notice: 'Coauthor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coauthor
      @coauthor = Coauthor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coauthor_params
      params.require(:coauthor).permit(:user_id, :book_id)
    end
end

app/helpers/coauthors_helper.rb
module CoauthorsHelper
end

app/views/coauthors/_form.html.erb
<%= form_for(coauthor) do |f| %>
  <% if coauthor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coauthor.errors.count, "error") %> prohibited this coauthor from being saved:</h2>

      <ul>
      <% coauthor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :book_id %>
    <%= f.text_field :book_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coauthors/edit.html.erb
<h1>Editing Coauthor</h1>

<%= render 'form', coauthor: @coauthor %>

<%= link_to 'Show', @coauthor %> |
<%= link_to 'Back', coauthors_path %>

app/views/coauthors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coauthors</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Book</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coauthors.each do |coauthor| %>
      <tr>
        <td><%= coauthor.user %></td>
        <td><%= coauthor.book %></td>
        <td><%= link_to 'Show', coauthor %></td>
        <td><%= link_to 'Edit', edit_coauthor_path(coauthor) %></td>
        <td><%= link_to 'Destroy', coauthor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coauthor', new_coauthor_path %>

app/views/coauthors/new.html.erb
<h1>New Coauthor</h1>

<%= render 'form', coauthor: @coauthor %>

<%= link_to 'Back', coauthors_path %>

app/views/coauthors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @coauthor.user %>
</p>

<p>
  <strong>Book:</strong>
  <%= @coauthor.book %>
</p>

<%= link_to 'Edit', edit_coauthor_path(@coauthor) %> |
<%= link_to 'Back', coauthors_path %>